---
name : tests
on :
  push :
    branches : [ "*" ]
  pull_request :
    types :
    - "opened"
    - "reopened"
    - "synchronize"

jobs :
  default :
    runs-on : ubuntu-latest
    steps :
    - name : checkout
      uses : "actions/checkout@v2"
      with : { fetch-depth : 0 }
    - name : go setup
      uses : "actions/setup-go@v2"
      with : { go-version : "1.13" }
    - name : go tests
      run : "cd tests && go test -timeout 60m -v"
